### ISSUE TITLE
Code overflows container when container is smaller than code.

### ISSUE THREAD

**Issue by goranmoomin** [karlicoss/beepb00p#1]
Code overflows the container when the container is smaller than the code. Below is a picture in macOS Safari Responsive Design Mode where the browser is sized 800x1024. You can see that the code overflows the container, and this makes it harder to see the article in mobile browsers.

![image](https://user-images.githubusercontent.com/37990858/73375912-e7b95d00-42ff-11ea-8b7d-ee3bacfe42db.png)

I believe that it can be fixed with this added to [`org-extra.css`](https://github.com/karlicoss/beepb00p/blob/master/css/org-extra.css):

```css
.org-src-container {
    position: relative;
}

pre.src {
    position: unset;
    overflow: auto;
}

pre.src:before {
    right: 30px;
}
```

It's making the `pre.src:before` element (the language indicator displayed when hovered) to be positioned relatively to the `.org-src-container` element instead of the `pre.src` element, and making `pre.src` scrollable when overflowed. (BTW, the [org-default.css](https://github.com/karlicoss/beepb00p/blob/master/css/org-default.css) has [lots of properties duplicated](https://github.com/gongzhitaao/orgcss/issues/10), looks like you should run a minifier to remove them.)

I believe this is a beneficial change, should I make a PR?
